apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontier-squid
  namespace: cvmfs
  labels:
    k8s-app: frontier-squid
spec:
  template:
    metadata: 
      labels:
        k8s-app: frontier-squid
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: nw
                operator: In
                values:
                - 100G
      containers:
      - name: frontier-squid
        image: opensciencegrid/frontier-squid:development
        imagePullPolicy: Always
        #command: ["sh", "-c", "sleep infinity"]
        ports:
        - containerPort: 3128

