apiVersion: v1
kind: Pod
metadata:
  name: frontier-squid
  namespace: cvmfs
  labels:
    k8s-app: frontier-squid
spec:
      nodeSelector: 
        kubernetes.io/hostname: k8s-gpu-03.sdsc.optiputer.net
      containers:
      - name: frontier-squid
        image: opensciencegrid/frontier-squid:development
        imagePullPolicy: Always
        #command: ["sh", "-c", "sleep infinity"]
        ports:
        - containerPort: 3128

