apiVersion: apps/v1
kind: Deployment
metadata:
  name: csicvmfs-demo-depl
  labels:
    app: csicvmfs-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csicvmfs-demo
  template:
    metadata:
      labels:
        app: csicvmfs-demo
    spec:
      containers:
       - name: demo
         image: busybox
         imagePullPolicy: IfNotPresent
         command: [ "/bin/sh", "-c", "trap : TERM INT; (while true; do sleep 1000; done) & wait" ]
         volumeMounts:
           - name: cvmfs-oasis
             mountPath: /cvmfs/oasis.opensciencegrid.org
           - name: cvmfs-config-osg
             mountPath: /cvmfs/config-osg.opensciencegrid.org
           - name: cvmfs-spt
             mountPath: /cvmfs/spt.opensciencegrid.org
           - name: cvmfs-connect
             mountPath: /cvmfs/connect.opensciencegrid.org
           - name: cvmfs-atlas
             mountPath: /cvmfs/atlas.cern.ch
           - name: cvmfs-atlas-condb
             mountPath: /cvmfs/atlas-condb.cern.ch
           - name: cvmfs-atlas-nightlies
             mountPath: /cvmfs/atlas-nightlies.cern.ch
           - name: cvmfs-sft
             mountPath: /cvmfs/sft.cern.ch
           - name: cvmfs-geant4
             mountPath: /cvmfs/geant4.cern.ch
           - name: cvmfs-grid
             mountPath: /cvmfs/grid.cern.ch
           - name: cvmfs-cms
             mountPath: /cvmfs/cms.cern.ch
      volumes:
       - name: cvmfs-oasis
         persistentVolumeClaim:
           claimName: csi-cvmfs-pvc-oasis
           readOnly: true
       - name: cvmfs-config-osg
         persistentVolumeClaim:
           claimName: csi-cvmfs-pvc-config-osg
       - name: cvmfs-spt
         persistentVolumeClaim:
           claimName: csi-cvmfs-pvc-spt
       - name: cvmfs-connect
         persistentVolumeClaim:
           claimName: csi-cvmfs-pvc-connect
       - name: cvmfs-atlas
         persistentVolumeClaim:
           claimName: csi-cvmfs-pvc-atlas
       - name: cvmfs-atlas-condb
         persistentVolumeClaim:
           claimName: csi-cvmfs-pvc-atlas-condb
       - name: cvmfs-atlas-nightlies
         persistentVolumeClaim:
           claimName: csi-cvmfs-pvc-atlas-nightlies
       - name: cvmfs-sft
         persistentVolumeClaim:
           claimName: csi-cvmfs-pvc-sft
       - name: cvmfs-geant4
         persistentVolumeClaim:
           claimName: csi-cvmfs-pvc-geant4
       - name: cvmfs-grid
         persistentVolumeClaim:
           claimName: csi-cvmfs-pvc-grid
       - name: cvmfs-cms
         persistentVolumeClaim:
           claimName: csi-cvmfs-pvc-cms